### ISSUE TITLE
Bug: Cannot restart kernel

### ISSUE THREAD

**Issue by cswarth** [sernst/cauldron#2]
Version Info: 
    cauldron-notebook (0.0.16, /Users/cswarth/Development/cauldron)
    Cauldron-1.270.509.dmg
```
$ python3 --version
Python 3.5.2
```

I don't appear to be able to restart the python kernel from the Cauldron MacOS UI.
Even if the UI is freshly started, I end up at a page that says "Applying Changes" with a spinning icon.  Is the kernel even running at this point, before I have actually created a notebook?

Reproduce with:

![screen shot 2016-09-23 at 9 51 38 am](https://cloud.githubusercontent.com/assets/295428/18794420/4c180a0e-8174-11e6-90a6-0a83cb74c776.png)
![screen shot 2016-09-23 at 9 51 47 am](https://cloud.githubusercontent.com/assets/295428/18794421/4c18b206-8174-11e6-8222-c52dfbe177c3.png)
![screen shot 2016-09-23 at 9 56 58 am](https://cloud.githubusercontent.com/assets/295428/18794422/4c19e496-8174-11e6-9630-a027195e3b4c.png)

**Comment by cswarth** [comment]
More info - when failing to reboot the kernel, Node is dying with following stack trace, 

```
[17923:0923/120517:INFO:CONSOLE(123)] "TypeError: Cannot read property 'source_directory' of undefined
    at file:///Applications/Cauldron.app/Contents/Resources/app.asar/scripts/bundle.js:2:8987
    at file:///Applications/Cauldron.app/Contents/Resources/app.asar/scripts/bower.js:136:20
    at m.$eval (file:///Applications/Cauldron.app/Contents/Resources/app.asar/scripts/bower.js:150:347)
    at m.$digest (file:///Applications/Cauldron.app/Contents/Resources/app.asar/scripts/bower.js:147:420)
    at file:///Applications/Cauldron.app/Contents/Resources/app.asar/scripts/bower.js:150:434
    at e (file:///Applications/Cauldron.app/Contents/Resources/app.asar/scripts/bower.js:50:444)
    at file:///Applications/Cauldron.app/Contents/Resources/app.asar/scripts/bower.js:53:300", source: file:///Applications/Cauldron.app/Contents/Resources/app.asar/scripts/bower.js (123)
```

**Comment by sernst** [comment]
Thanks for the detailed information on this one. I've resolved the issue in the latest release.
