### ISSUE TITLE
Breaking change for notebook tests from 0.4.6 to 0.4.7

### ISSUE THREAD

**Issue by kjschiroo** [sernst/cauldron#64]
When multiple tests are configured in a `StepTestCase` instance only one allowed to succeed, the others error out. Here is a minimal example:

```python
from cauldron.steptest import StepTestCase

class TestNotebook(StepTestCase):

    def test_one(self):
        self.run_step('S01-Initialize.py')

    def test_two(self):
        self.run_step('S01-Initialize.py')
```

the following error results

```
__________________________________________________________________________________________ TestNotebook.test_two ___________________________________________________________________________________________

self = <test.test_notebook.TestNotebook testMethod=test_two>

    def open_project(self) -> 'exposed.ExposedProject':
        """
        Opens the project associated with this test and returns the public
        (exposed) project after it has been loaded. If the project cannot be
        opened the test will fail.
        """
        try:
            project_path = self.make_project_path()
>           return support.open_project(project_path)

/usr/local/lib/python3.7/site-packages/cauldron/steptest/__init__.py:80:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

project_path = '/Users/kevinschiroo/path/to/project/notebook'

    def open_project(project_path: str) -> 'exposed.ExposedProject':
        """
        Opens the project located at the specified path and returns the public
        (exposed) project after it has been loaded. If the project cannot be
        opened a `RuntimeError` will be raised instead.

        :param project_path:
            The path to the Cauldron project to open. It should be either a
            directory that contains a `cauldron.json` file or a file path to the
            `cauldron.json` file for the project to load.
        """
        res = commander.execute(
            name='open',
            raw_args='{} --forget'.format(project_path),
            response=environ.Response()
        )
        res.thread.join()

        # Prevent threading race conditions
        project = (
            cd.project.get_internal_project()
            if res.success else
            None
        )

        if res.failed or not project:
            raise RuntimeError(
>               'Unable to open project at path "{}"'.format(project_path)
            )
E           RuntimeError: Unable to open project at path "/Users/kevinschiroo/path/to/project/notebook"

/usr/local/lib/python3.7/site-packages/cauldron/steptest/support.py:66: RuntimeError

During handling of the above exception, another exception occurred:
/usr/local/lib/python3.7/site-packages/cauldron/steptest/__init__.py:50: in setUp
    self.open_project()
/usr/local/lib/python3.7/site-packages/cauldron/steptest/__init__.py:82: in open_project
    self.fail('{}'.format(error))
E   AssertionError: Unable to open project at path "/Users/kevinschiroo/path/to/project/notebook"
------------------------------------------------------------------------------------------- Captured stdout call -------------------------------------------------------------------------------------------
spec not found for the module 'test.test_notebook'

[ERROR]: Failed to execute command due to internal error

------------------------------------------------------------------------------------------- Captured stderr call -------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cauldron/cli/threads.py", line 62, in run_command
    **self.kwargs
  File "/usr/local/lib/python3.7/site-packages/cauldron/cli/commands/open/__init__.py", line 147, in execute
    results_path=results_path
  File "/usr/local/lib/python3.7/site-packages/cauldron/cli/commands/open/opener.py", line 177, in open_project
    runner.reload_libraries(project.library_directories)
  File "/usr/local/lib/python3.7/site-packages/cauldron/runner/__init__.py", line 120, in reload_libraries
    for directory in directories
  File "/usr/local/lib/python3.7/site-packages/cauldron/runner/__init__.py", line 121, in <listcomp>
    for reloaded_module in reload_library(directory)
  File "/usr/local/lib/python3.7/site-packages/cauldron/runner/__init__.py", line 115, in reload_library
    for path in glob.glob(glob_path, recursive=True)
  File "/usr/local/lib/python3.7/site-packages/cauldron/runner/__init__.py", line 115, in <listcomp>
    for path in glob.glob(glob_path, recursive=True)
  File "/usr/local/lib/python3.7/site-packages/cauldron/runner/__init__.py", line 102, in reload_module
    return importlib.reload(module) if module is not None else None
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 168, in reload
    raise ModuleNotFoundError(f"spec not found for the module {name!r}", name=name)
ModuleNotFoundError: spec not found for the module 'test.test_notebook'
```

Commenting out each test one at a time the uncommented test succeeds.

This appears to be a change from 0.4.6 to 0.4.7. In 0.4.6 these tests pass, in 0.4.7 one fails.

**Comment by kjschiroo** [comment]
After further investigation this appears to only be affecting Mac specifically. Linux does not see these issues.

**Comment by sernst** [comment]
Turns out the issue here was that Python has an internal `test` standard library package that is being exposed on mac, which made importing tests from a `test` folder in the notebook impossible due to prioritized loading of the standard library package. The resolution here is to recommend that tests be placed in a `step_tests` folder to prevent such conflict from occurring. The website was updated in the 1.0.0 release to reflect this more clearly.
