### ISSUE TITLE
Remove deprecated jinja2 contextfilter

### ISSUE THREAD

**Issue by njgohman** [sernst/cauldron#86]
Seeing import errors because `contextfilter` has been removed from `jinja2`. It's been replaced by `jinja2.pass_context`.

**Comment by njgohman** [comment]
```
>>> import cauldron as cd
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    import cauldron as cd
  File "/Users/gohmann/src/self/poem/.env/lib/python3.9/site-packages/cauldron/__init__.py", line 3,
 in <module>
    from cauldron import session as _session
  File "/Users/gohmann/src/self/poem/.env/lib/python3.9/site-packages/cauldron/session/__init__.py",
 line 5, in <module>
    from cauldron.session.exposed import ExposedProject
  File "/Users/gohmann/src/self/poem/.env/lib/python3.9/site-packages/cauldron/session/exposed.py",
line 7, in <module>
    from cauldron import templating
  File "/Users/gohmann/src/self/poem/.env/lib/python3.9/site-packages/cauldron/templating.py", line
11, in <module>
    from jinja2 import contextfilter
ImportError: cannot import name 'contextfilter' from 'jinja2' (/Users/gohmann/src/self/poem/.env/lib
/python3.9/site-packages/jinja2/__init__.py)
```
